# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

exporters:
  otlp/bugsnag:
    endpoint: 567dad9b9079245fca36acfa85d5e5e7.otlp.bugsnag.com:4317
    compression: none
service:
  pipelines:
    traces:
      exporters: [spanmetrics, otlp/bugsnag]
